// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt3WsW_CWzsmWLXI4mXlQ37ZLkn5n_fmM',
    appId: '1:118109128001:web:7736f15e430ec2dfb20dc0',
    messagingSenderId: '118109128001',
    projectId: 'nebula-55342',
    authDomain: 'nebula-55342.firebaseapp.com',
    storageBucket: 'nebula-55342.appspot.com',
    measurementId: 'G-B540DNHWHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHs493yNWhNNPwo7nRBm9EZT_I6Re2GBU',
    appId: '1:118109128001:android:fb1c9b9aad96aec0b20dc0',
    messagingSenderId: '118109128001',
    projectId: 'nebula-55342',
    storageBucket: 'nebula-55342.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8UQTeYd_1DFQuluPDJxSSk_6JZyDkAKE',
    appId: '1:118109128001:ios:e7507b55d8b0ccc4b20dc0',
    messagingSenderId: '118109128001',
    projectId: 'nebula-55342',
    storageBucket: 'nebula-55342.appspot.com',
    iosClientId: '118109128001-2u9e8qj8p60u6sinfpgv0in0rq1et078.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelNebula',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8UQTeYd_1DFQuluPDJxSSk_6JZyDkAKE',
    appId: '1:118109128001:ios:fd41ab0293d58448b20dc0',
    messagingSenderId: '118109128001',
    projectId: 'nebula-55342',
    storageBucket: 'nebula-55342.appspot.com',
    iosClientId: '118109128001-01oc9cijmdrhpgc2pa9rmrb4ob2kgabo.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelNebula.RunnerTests',
  );
}
